# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('link', models.URLField(max_length=1000, verbose_name='link')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'verbose_name': 'entry',
            },
        ),
        migrations.CreateModel(
            name='EntryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'entry categories',
                'verbose_name': 'entry category',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rss.EntryCategory', verbose_name='category'),
        ),
    ]
